-- ============================================================================
--  Berkeley Networking Tracker -- database schema
--  Run this once in the Neon Console SQL Editor (it runs as the database owner).
--  Safe to re-run: every statement is idempotent.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. The contacts table
--
--    user_id is the ownership column. It is `text` (not uuid) because Neon Auth
--    puts the user's id in the JWT `sub` claim as a string, and auth.user_id()
--    returns exactly that. It DEFAULTs to auth.user_id() so a client physically
--    cannot forget to set it, and it is NOT NULL so an unauthenticated caller
--    (where auth.user_id() is NULL) cannot insert an orphan row.
--
--    The CHECK constraints are database-level validation: even if every line of
--    application code were bypassed, Postgres itself refuses a blank name or a
--    priority outside the three allowed values.
-- ---------------------------------------------------------------------------
create table if not exists public.contacts (
  id          bigint generated by default as identity primary key,
  user_id     text        not null default (auth.user_id()),
  name        text        not null,
  company     text,
  role        text,
  where_met   text,
  notes       text,
  priority    text        not null default 'medium',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint contacts_name_not_blank
    check (length(btrim(name)) > 0),
  constraint contacts_priority_allowed
    check (priority in ('high', 'medium', 'low'))
);

-- Index the ownership column: every RLS-filtered query includes user_id.
create index if not exists contacts_user_id_idx on public.contacts (user_id);

-- ---------------------------------------------------------------------------
-- 2. Keep updated_at honest
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists contacts_set_updated_at on public.contacts;
create trigger contacts_set_updated_at
  before update on public.contacts
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. Row Level Security
--
--    Without this line, the policies below are inert. With it, Postgres denies
--    every row by default and only the policies can let a row through.
-- ---------------------------------------------------------------------------
alter table public.contacts enable row level security;

-- Belt and braces: also enforce RLS against the table owner, so nothing
-- accidentally runs with an implicit bypass.
alter table public.contacts force row level security;

-- Four SEPARATE policies, one per operation, as the spec requires.
--
--   USING      -> "which existing rows may I see / act on?"
--   WITH CHECK -> "what is the row allowed to look like AFTER I write it?"
--
-- The UPDATE policy needs BOTH. USING stops you editing someone else's row.
-- WITH CHECK stops you taking your own row and reassigning user_id to someone
-- else -- which is the specific attack the assignment asks us to block.

drop policy if exists contacts_select_own on public.contacts;
create policy contacts_select_own
  on public.contacts
  for select
  to authenticated
  using (auth.user_id() = user_id);

drop policy if exists contacts_insert_own on public.contacts;
create policy contacts_insert_own
  on public.contacts
  for insert
  to authenticated
  with check (auth.user_id() = user_id);

drop policy if exists contacts_update_own on public.contacts;
create policy contacts_update_own
  on public.contacts
  for update
  to authenticated
  using (auth.user_id() = user_id)
  with check (auth.user_id() = user_id);

drop policy if exists contacts_delete_own on public.contacts;
create policy contacts_delete_own
  on public.contacts
  for delete
  to authenticated
  using (auth.user_id() = user_id);

-- ---------------------------------------------------------------------------
-- 4. Grants for the Data API
--
--    RLS decides WHICH ROWS. Grants decide WHETHER THE ROLE MAY ASK AT ALL.
--    You need both. `authenticated` is the role the Data API assumes once it
--    has verified a user's JWT; `anonymous` is a signed-out caller and gets nothing.
-- ---------------------------------------------------------------------------
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.contacts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on public.contacts from anonymous;

-- ---------------------------------------------------------------------------
-- 5. Verification queries -- run these to prove the setup to a grader
-- ---------------------------------------------------------------------------
-- Is RLS on?
--   select relname, relrowsecurity, relforcerowsecurity
--   from pg_class where relname = 'contacts';
--
-- What policies exist?
--   select policyname, cmd, roles, qual as using_expr, with_check as check_expr
--   from pg_policies where tablename = 'contacts' order by cmd;
--
-- What does the table look like?
--   select column_name, data_type, is_nullable, column_default
--   from information_schema.columns
--   where table_name = 'contacts' order by ordinal_position;
